# NumPy Essentials

### Basic Array Creation:

In [10]:
import numpy as np

a = np.array([1,2,3])               # 1D array/tensor  [1 2 3]

b = np.array([[1,2,3], [4,5,6]])    # 2D array/tensor  [[1 2 3]
                                    #           [4 5 6]]

c = np.zeros((3,3,3))               # 3D tensor of zeroes
                                    # [[[0. 0. 0.]
                                    #   [0. 0. 0.]
                                    #   [0. 0. 0.]]

                                    #  [[0. 0. 0.]
                                    #   [0. 0. 0.]
                                    #   [0. 0. 0.]]

                                    #  [[0. 0. 0.]
                                    #   [0. 0. 0.]
                                    #   [0. 0. 0.]]]


d = np.ones((2, 4))                 # 2D tensor of ones
                                    # [[1. 1. 1. 1.]
                                    #  [1. 1. 1. 1.]]

e = np.eye(3)                       # identity matrix
                                    # [[1. 0. 0.]
                                    #  [0. 1. 0.]
                                    #  [0. 0. 1.]]


f = np.random.random((2, 2))         # random values
                                    # [[0.37699864 0.25810566]
                                    #  [0.037246   0.45232324]]



# Array attributes

print(a.ndim)                       # number of dimensions 
                                        # prints 1

print(b.shape)                      # shape of array
                                        # prints (2, 3). 2 for number of arrays, 3 for number of elements per array

print(c.size)                       # total number of elements
                                        # prints 27

print(d.dtype)                      # data type
                                        # prints float64

print(e.itemsize)                   # size in bytes of each element
                                        # prints 8 (recall: 1 byte = 8 bits. so 8 bytes = 64 bits)

print(f.nbytes)                     # total bytes consumed by array

1
(2, 3)
27
float64
8
32


### Memory Layout: 
how tensor data is physically arranged in computer memory.

In [13]:
x = np.array([[1,2,3], [4,5,6]], order='C')
print(x.flags.c_contiguous)     # Is it C-contiguous? True


True


In [12]:
y = x = np.array([[1,2,3], [4,5,6]], order='F')
print(y.flags.f_contiguous)     # Is it Fortran contiguous? 

True


### Basic Operations

In [21]:
# Element-wise operations
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)                  # addition [5, 7, 9]
print(a * b)                # element-wise multiplication [4, 10, 18]
print(np.dot(a,b))          # dot product/sum(a*b) : 32

[5 7 9]
[ 4 10 18]
32


In [23]:
# Matrix operations
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(A @ B)                # matrix multiplication
print("\n")
print(np.matmul(A,B))       # same as above

[[19 22]
 [43 50]]


[[19 22]
 [43 50]]


#### Vectorized Operations

In [ ]:
a = np.array([1,2,3])
print(a + 5)            # adds 5 to each element in the array

[6 7 8]


In [24]:
batch = np.random.randn(32, 10, 10)     # batch of 32 10x10 matrices
result = np.sum(batch, axis=0)          # sum across batch dimension

print(result)

[[ -0.02447243  -4.58678592   2.79514857   4.37957598  -5.01027197
    0.79991992   1.06516404  -6.75187828  -5.5635052   -2.75984379]
 [  5.07939064  -6.08044128  -2.0107042   -3.23687038  -1.9939912
   -1.43513934   4.59965931  -1.24282259  -4.99097576  11.89869832]
 [ -1.54279366  -5.47952922   3.42598619   4.50755354   3.87820602
   -4.19837516   2.73886503  -5.62062562   4.98620218   4.14222144]
 [ 10.81880802  -3.0316239    1.3985158   -8.4999524    8.4718774
    6.96113947   7.70438246   0.23762215  -1.93385122   3.39785957]
 [  2.22880788   2.62092499   1.47809868  -0.47977848   4.65140253
   -0.25928333   5.94391666   4.55825208  -3.7509756   -8.45029718]
 [ -1.25629205  -0.51275671  -8.27743996   1.48546517   0.08115635
    4.33144519 -12.68775831   5.41431455  -0.59448426  -7.32965964]
 [ -1.39553701 -14.52411923  -0.93647355  -2.92908507  -0.73956153
    2.17402357  -1.53052591 -11.38280558  -4.81727417   6.00257577]
 [ -2.49392955  -3.25959384  -0.51832825  -5.34498951   7

#### Memory Views and Slicing


- A **view** is a reference/alias of an object (point to same location in memory). Changes to the original object change the view and vice versa.

For example, 

```
my_array = np.arange(10)
print(my_array)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Take a portion of the array from index 2 to index 5 (not including 5)
slice_of_array = my_array[2:5]
print(slice_of_array)  # [2, 3, 4]
```

This creates a "view" - which means slice_of_array is looking at the same data as my_array, just a smaller portion of it.

In [36]:
# Slicing creates views, not copies

a = np.arange(10)           # an array 0-9 inclusive. [0 1 2 3 4 5 6 7 8 9]
b = a[2:5]                  # [2 3 4]
b[0] = 99                   # [99 3 4]
print(a)                    # [ 0  1 99  3  4  5  6  7  8  9]


# Explicit copy

c = a[2:5].copy()
c[0] = 42                   # This doesn't affect a
print(a)                    # [0, 1, 99, 3, 4, 5, 6, 7, 8, 9]

[ 0  1 99  3  4  5  6  7  8  9]
[ 0  1 99  3  4  5  6  7  8  9]


In [37]:
# EXAMPLE OF VIEWS

# Original array
original = np.array([10, 20, 30, 40, 50])

# Create two different views of the same array
view1 = original[1:4]      # [20, 30, 40]
view2 = original[::2]      # [10, 30, 50]

# Modify through the first view
view1[0] = 999             # Changes original[1] to 999

print("After modifying through view1:")
print("original:", original)  # [10, 999, 30, 40, 50]
print("view1:", view1)        # [999, 30, 40]
print("view2:", view2)        # [10, 30, 50]  (view2[1] not affected as it's original[2])

# Modify through the original
original[2] = 888

print("\nAfter modifying through original:")
print("original:", original)  # [10, 999, 888, 40, 50]
print("view1:", view1)        # [999, 888, 40]
print("view2:", view2)        # [10, 888, 50]  (view2[1] is affected as it's original[2])

After modifying through view1:
original: [ 10 999  30  40  50]
view1: [999  30  40]
view2: [10 30 50]

After modifying through original:
original: [ 10 999 888  40  50]
view1: [999 888  40]
view2: [ 10 888  50]


### NumPy Internals

#### Strides

In [32]:
# strides
x = np.array([[1,2,3], 
              [4,5,6]], 
              dtype=np.int32)

print(x.strides)        # bytes to step in each dimension

(12, 4)


The output is (12, 4).

Each element’s size in memory = number of bytes needed to store its value. <br>
`dtype=np.int32` means each element is a **32-bit** integer → **4 bytes** <br>
(32 bits ÷ 8 bits per byte = 4 bytes)

- First number (12) → # of bytes to move **to the next row** (axis 0)
    - each row has 3 elements x 4 bytes = 12 bytes
- Second number (4) → bytes to move **to the next column** (axis 1)
    - each step within a row moves by 1 element → 4 bytes


##### Intuition:

Think of the array as **flattened memory**:

`[1, 2, 3, 4, 5, 6]  ← all stored in a contiguous memory block`

- from `1 → 2` → +4 bytes (column move)
- from `1 → 4` → +12 bytes (row move)


##### Using `numpy.lib.strides_tricks`

In [ ]:
from numpy.lib.stride_tricks import as_strided

# Create a sliding window view (important pattern for convolutions)
# For int64 arrays, each element is 8 bytes
# Element stride of 1 = 8 bytes, for the sliding window

a = np.arange(10)
windows = as_strided(a, shape=(6, 3), strides=(8, 8))
print(windows)

# [[0 1 2]
#  [1 2 3]
#  [2 3 4]
#  [3 4 5]
#  [4 5 6]
#  [5 6 7]]

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


Each row is one "window" into our original array.